# Generated by Django 3.1.2 on 2020-12-06 13:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201129_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', help_text='Small description about user in 500 characters', max_length=500, verbose_name='User Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img/default_profile.jpg', null=True, upload_to=users.models.upload_profile, verbose_name='User Profile Pic'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
