# Generated by Django 3.1.2 on 2020-12-06 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0006_auto_20201206_1339'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selling_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='When transaction is made')),
                ('expiration_time', models.DateTimeField(verbose_name='When will this transaction expire')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_bought', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_sold', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tools.tool')),
            ],
        ),
    ]
