# Generated by Django 3.1.2 on 2020-12-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20201207_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
