# Generated by Django 3.1.2 on 2020-12-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_cost_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cost_per_day',
            new_name='cost_per_hour',
        ),
    ]
