# Generated by Django 3.1.2 on 2020-12-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20201207_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created',)},
        ),
    ]
