# Generated by Django 3.1.2 on 2020-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(blank=True, help_text='How will you rate this tool out of 5', null=True, verbose_name='Stars'),
        ),
    ]
