# Generated by Django 3.1.2 on 2020-10-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=False, help_text='Is this tool available right now or not ?', verbose_name='Status'),
        ),
    ]
