# Generated by Django 3.1.2 on 2020-10-16 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_alt_text', models.CharField(max_length=50, verbose_name='Alt Text for image')),
                ('image', models.ImageField(blank=True, help_text='Add Image', null=True, upload_to=tools.models.upload_to_aws_s3, verbose_name='Picture')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name of Tool')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.IntegerField(blank=True, help_text='How many of these you have ?', null=True, verbose_name='Quantity')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Price of the Tool')),
                ('status', models.BooleanField(default=False, help_text='Is this tool available right now or not ?', verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
