# Generated by Django 3.1.2 on 2020-10-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'available'), ('Not avaiable', 'not_available')], help_text='Is this tool available right now or not ?', max_length=40, null=True, verbose_name='Status'),
        ),
    ]
