# Generated by Django 3.1.2 on 2020-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20201017_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Images of this tool.', to='tools.Picture'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('not_available', 'Not available')], help_text='Is this tool available right now or not ?', max_length=40, null=True, verbose_name='Status'),
        ),
    ]
