# Generated by Django 3.1.2 on 2020-10-14 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_alt_text', models.CharField(max_length=50, verbose_name='Alt Text for image')),
                ('image', models.ImageField(upload_to='', verbose_name='Picture')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
