# Generated by Django 3.1.2 on 2020-10-14 18:02

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, help_text='Add Image', null=True, upload_to=tools.models.upload_to_aws_s3, verbose_name='Picture'),
        ),
    ]
