# Generated by Django 3.1.2 on 2020-10-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20201017_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='images',
            field=models.ManyToManyField(help_text='Images of this tool.', to='tools.Picture'),
        ),
    ]
