# Generated by Django 3.1.2 on 2020-10-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20201017_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Images of this tool.', to='tools.Picture'),
        ),
    ]
