# Generated by Django 3.1.2 on 2020-12-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20201024_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-timestamp']},
        ),
    ]
