# Generated by Django 3.1.2 on 2020-12-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20201206_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='cost',
        ),
        migrations.AddField(
            model_name='tool',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Cost per day in INR.'),
        ),
    ]
