# Generated by Django 3.1.2 on 2020-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20201207_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='cost_per_day',
        ),
        migrations.AddField(
            model_name='tool',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Cost per hour in INR.'),
        ),
    ]
