# Generated by Django 3.1.2 on 2020-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20201207_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='tool',
            name='total_stars',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='total_users_rated',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
