# Generated by Django 3.1.2 on 2020-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20201208_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tool',
            name='total_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='total_users_rated',
            field=models.IntegerField(default=0),
        ),
    ]
