# Generated by Django 3.1.2 on 2020-12-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20201212_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
